[package]
name = "contracts"
edition = "2024"         # edition = "legacy" to use legacy (pre-2024) Move
license = "MIT"           # e.g., "MIT", "GPL", "Apache 2.0"
authors = ["Hrishikesh Rana(itsranahrishikesh@gmail.com)"]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
deepbook = { git  = "https://github.com/MystenLabs/deepbookv3.git",subdir = "packages/deepbook",rev = "main"}

[addresses]
deepbookv3 = "0x337f4f4f6567fcd778d5454f27c16c70e2f274cc6377ea6249ddf491482ef497"

# Read more about the package management system options:
# https://docs.sui.io/guides/developer/sui-101/move-package-management
