[package]
name = "contracts"
edition = "2024"         # edition = "legacy" to use legacy (pre-2024) Move
# license = "MIT"           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["Hrishikesh Rana(itsranahrishikesh@gmail.com)"]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]

# Read more about the package management system options:
# https://docs.sui.io/guides/developer/sui-101/move-package-management
